version: "3"
networks:
  docker-homeserver:
    external: true
services:
  sonarr:
    image: linuxserver/sonarr
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sonarr.${SITE_BASE_DOMAIN}"
      - "traefik.port=8989"
      - traefik.frontend.auth.basic.usersFile=/.htpasswd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SHARE_PATH}/sonarr:/config
      - ${MEDIA_PATH1}:/d
      - ${MEDIA_PATH2}:/f
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    networks:
      - docker-homeserver
    restart: always
