version: "3"
services:
  hass:
    image: homeassistant/home-assistant
    container_name: hass
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SHARE_PATH}/hass:/config
    restart: always
