version: "3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ${SHARE_PATH}/plex:/config
      - ${MEDIA_PATH1}:/d
      - ${MEDIA_PATH2}:/f
    network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - ADVERTISE_IP=http://10.0.0.123:32400/
      - PLEX_UID=0
      - PLEX_GID=0
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
    restart: always
