version: "3"
services:
  traefik:
    image: traefik:1.7
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - ${PORT_PREFIX}01:8080 # webui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHARE_PATH}/traefik/traefik.toml:/traefik.toml
      - ${SHARE_PATH}/traefik/.htpasswd:/.htpasswd
      - ${SHARE_PATH}/traefik/acme.json:/acme.json
    command: --api
    networks:
      - docker-homeserver
networks:
  docker-homeserver:
    external: true
