version: "3"
networks:
  docker-homeserver:
    external: true
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:radarr.${SITE_BASE_DOMAIN}"
      - "traefik.port=7878"
      - "traefik.frontend.auth.basic.usersFile=/.htpasswd"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SHARE_PATH}/radarr:/config
      - ${MEDIA_PATH1}:/d
      - ${MEDIA_PATH2}:/f
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    networks:
      - docker-homeserver
    restart: always
